#include <stdio.h>
#include <stdlib.h>

// TODO Вынести объявления в отдельный .h-файл

typedef struct metastr{
	int length;
	char* data;
} metastr;

typedef void (*cb)(char);

void run_callback(char);
void magic_run(metastr, cb);

int main()
{
	char c[10] = "abcdefghi";
	metastr mts = {.length = 10, .data = c} // не совсем верно

	for (int i = 0; i < 10; ++i)
	{
		run_callback(c[i]);
	}

	magic_run(mts, run_callback);

	return 0;
}

void run_callback(char h) {
	printf("%c\n", h);
}

void magic_run(metastr mts, rcb)
{
	for (int i = 0; i < cb.length; i++)
		rcb(mts.data[i]);
}